### ISSUE TITLE
train中def test和model的问题

### ISSUE THREAD

**Issue by mk123qwe** [CharlesPikachu/deeplearningtoys#1]
train中def test和model的最后一层来看，其实这做了一个图像 to（0，1，2，3）的回归问题。
但demo里又用到了softmax分类问题，其实lable没有做one-hot？

**Comment by CharlesPikachu** [comment]
refer https://pytorch.org/docs/0.4.1/nn.html?highlight=cross_entropy#crossentropyloss please.
